name: windows_unit_tests
description: A new flutter plugin project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: WindowsUnitTestsPluginCApi

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
